dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: mvn -v
script: mvn -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: DSEasNJ+FFh/StYbYTOsBX1hVcAVeY+bGiSPZK7MiI6tMz7/Gj93RWalTGDxIE4pOs5XSzfbC+zOtdtXIV7oUGgV6xkjpfnD5onTKhUvOCDyjjgLE4HEs/ab1poEwUnUZ0yP+XNvCSmTSbClTi6JRltH6NMJWFiJ/S7Xo4nlpJW6rFO6WtNZlnFWcYA+lsL+UBiOEOtuXRWBewfo2li6qzqHKguNCsjxgpcqR6NH3H5fxM1K6QkL0tdfUOhe2UA0K6O+/aOlXV4qit7I7nf2SkDJWSyZMCFFCk9+lZFCIm+8w1oSvMLV/qNHKQUexjZzw/yNv9H5xsISsP5ek50N7bpdrI6iNRpgY1OjzHa0IZJ4GeUUGBpd/QJryUWxvcbGcIMhFpQcqzEcq1RtYMBZqTv8+Oefo/5+V3EprDZ2SUlBUbeJK+DGM81zFZNXoBWm3jW9WFHTMK3Z0gKXjdSvIkxolPyFV+vMbEHu/hO/1SXlF46CzQ4Upjsi+n+HYIf2zcZg2O/tIxKUtgldSTZKbU2lPDMJnAkZ5VaP9PHkidQjJwpnehupxMuLeaK3HKAaRbctLbjqbU0kLSKvWc8fj4CO3SUuvwet1qqXH2/VPf6+fwmDZXY4lSmzjTx2KaZW75qIXBUK598Vo4Bvm8STf0LNFrjJTyY5RQtUcP4R6oI=
